baseURL = 'https://tinytapeout.com'
languageCode = 'en-us'
title = 'Tiny Tapeout'
theme = "learn"

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1

[params]
    Description = "Quicker, easier and cheaper than ever to make your own chip!"
    themeVariant = "tinytapeout"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation in English"
weight = 1
languageName = "English"

[Languages.es]
title = "Documentation en Español"
weight = 2
languageName = "Español"
